    // 路径配置
		require.config({
			paths: {
				echarts: './echarts/build/dist',
			}
		});

		// 使用
		require(
			[
				'echarts',  //必须是echarts
				'echarts/chart/map' // 使用柱状图就加载bar模块，按需加载
			],
			function(ecMain) {

				var myChartMain = ecMain.init(document.getElementById('main'));
				var ecConfig = require('echarts/config');
				//var zrEvent = require('zrender/tool/event');
				//var curIndx = 0;
				var mapType = [
					'china',
					// 23个省
					'广东', '青海', '四川', '海南', '陕西',
					'甘肃', '云南', '湖南', '湖北', '黑龙江',
					'贵州', '山东', '江西', '河南', '河北',
					'山西', '安徽', '福建', '浙江', '江苏',
					'吉林', '辽宁', '台湾',
					// 5个自治区
					'新疆', '广西', '宁夏', '内蒙古', '西藏',
					// 4个直辖市
					'北京', '天津', '上海', '重庆',
					// 2个特别行政区
					'香港', '澳门',
				];

        //所有的城市数据
				var cityMap = {
					"北京市": "110100",
					"天津市": "120100",
					"上海市": "310100",
					"重庆市": "500100",

					"崇明县": "310200", //
					"湖北省直辖县市": "429000", //
					"铜仁市": "522200", //
					"毕节市": "522400", //

					"石家庄市": "130100",
					"唐山市": "130200",
					"秦皇岛市": "130300",
					"邯郸市": "130400",
					"邢台市": "130500",
					"保定市": "130600",
					"张家口市": "130700",
					"承德市": "130800",
					"沧州市": "130900",
					"廊坊市": "13100",
					"衡水市": "131100",
					"太原市": "140100",
					"大同市": "140200",
					"阳泉市": "140300",
					"长治市": "140400",
					"晋城市": "140500",
					"朔州市": "140600",
					"晋中市": "140700",
					"运城市": "140800",
					"忻州市": "140900",
					"临汾市": "14100",
					"吕梁市": "141100",
					"呼和浩特市": "150100",
					"包头市": "150200",
					"乌海市": "150300",
					"赤峰市": "150400",
					"通辽市": "150500",
					"鄂尔多斯市": "150600",
					"呼伦贝尔市": "150700",
					"巴彦淖尔市": "150800",
					"乌兰察布市": "150900",
					"兴安盟": "152200",
					"锡林郭勒盟": "152500",
					"阿拉善盟": "152900",
					"沈阳市": "210100",
					"大连市": "210200",
					"鞍山市": "210300",
					"抚顺市": "210400",
					"本溪市": "210500",
					"丹东市": "210600",
					"锦州市": "210700",
					"营口市": "210800",
					"阜新市": "210900",
					"辽阳市": "21100",
					"盘锦市": "211100",
					"铁岭市": "211200",
					"朝阳市": "211300",
					"葫芦岛市": "211400",
					"长春市": "220100",
					"吉林市": "220200",
					"四平市": "220300",
					"辽源市": "220400",
					"通化市": "220500",
					"白山市": "220600",
					"松原市": "220700",
					"白城市": "220800",
					"延边朝鲜族自治州": "222400",
					"哈尔滨市": "230100",
					"齐齐哈尔市": "230200",
					"鸡西市": "230300",
					"鹤岗市": "230400",
					"双鸭山市": "230500",
					"大庆市": "230600",
					"伊春市": "230700",
					"佳木斯市": "230800",
					"七台河市": "230900",
					"牡丹江市": "23100",
					"黑河市": "231100",
					"绥化市": "231200",
					"大兴安岭地区": "232700",
					"南京市": "320100",
					"无锡市": "320200",
					"徐州市": "320300",
					"常州市": "320400",
					"苏州市": "320500",
					"南通市": "320600",
					"连云港市": "320700",
					"淮安市": "320800",
					"盐城市": "320900",
					"扬州市": "32100",
					"镇江市": "321100",
					"泰州市": "321200",
					"宿迁市": "321300",
					"杭州市": "330100",
					"宁波市": "330200",
					"温州市": "330300",
					"嘉兴市": "330400",
					"湖州市": "330500",
					"绍兴市": "330600",
					"金华市": "330700",
					"衢州市": "330800",
					"舟山市": "330900",
					"台州市": "33100",
					"丽水市": "331100",
					"合肥市": "340100",
					"芜湖市": "340200",
					"蚌埠市": "340300",
					"淮南市": "340400",
					"马鞍山市": "340500",
					"淮北市": "340600",
					"铜陵市": "340700",
					"安庆市": "340800",
					"黄山市": "34100",
					"滁州市": "341100",
					"阜阳市": "341200",
					"宿州市": "341300",
					"六安市": "341500",
					"亳州市": "341600",
					"池州市": "341700",
					"宣城市": "341800",
					"福州市": "350100",
					"厦门市": "350200",
					"莆田市": "350300",
					"三明市": "350400",
					"泉州市": "350500",
					"漳州市": "350600",
					"南平市": "350700",
					"龙岩市": "350800",
					"宁德市": "350900",
					"南昌市": "360100",
					"景德镇市": "360200",
					"萍乡市": "360300",
					"九江市": "360400",
					"新余市": "360500",
					"鹰潭市": "360600",
					"赣州市": "360700",
					"吉安市": "360800",
					"宜春市": "360900",
					"抚州市": "36100",
					"上饶市": "361100",
					"济南市": "370100",
					"青岛市": "370200",
					"淄博市": "370300",
					"枣庄市": "370400",
					"东营市": "370500",
					"烟台市": "370600",
					"潍坊市": "370700",
					"济宁市": "370800",
					"泰安市": "370900",
					"威海市": "37100",
					"日照市": "371100",
					"莱芜市": "371200",
					"临沂市": "371300",
					"德州市": "371400",
					"聊城市": "371500",
					"滨州市": "371600",
					"菏泽市": "371700",
					"郑州市": "410100",
					"开封市": "410200",
					"洛阳市": "410300",
					"平顶山市": "410400",
					"安阳市": "410500",
					"鹤壁市": "410600",
					"新乡市": "410700",
					"焦作市": "410800",
					"濮阳市": "410900",
					"许昌市": "41100",
					"漯河市": "411100",
					"三门峡市": "411200",
					"南阳市": "411300",
					"商丘市": "411400",
					"信阳市": "411500",
					"周口市": "411600",
					"驻马店市": "411700",
					"省直辖县级行政区划": "469000",
					"武汉市": "420100",
					"黄石市": "420200",
					"十堰市": "420300",
					"宜昌市": "420500",
					"襄阳市": "420600",
					"鄂州市": "420700",
					"荆门市": "420800",
					"孝感市": "420900",
					"荆州市": "42100",
					"黄冈市": "421100",
					"咸宁市": "421200",
					"随州市": "421300",
					"恩施土家族苗族自治州": "422800",
					"长沙市": "430100",
					"株洲市": "430200",
					"湘潭市": "430300",
					"衡阳市": "430400",
					"邵阳市": "430500",
					"岳阳市": "430600",
					"常德市": "430700",
					"张家界市": "430800",
					"益阳市": "430900",
					"郴州市": "43100",
					"永州市": "431100",
					"怀化市": "431200",
					"娄底市": "431300",
					"湘西土家族苗族自治州": "433100",
					"广州市": "440100",
					"韶关市": "440200",
					"深圳市": "440300",
					"珠海市": "440400",
					"汕头市": "440500",
					"佛山市": "440600",
					"江门市": "440700",
					"湛江市": "440800",
					"茂名市": "440900",
					"肇庆市": "441200",
					"惠州市": "441300",
					"梅州市": "441400",
					"汕尾市": "441500",
					"河源市": "441600",
					"阳江市": "441700",
					"清远市": "441800",
					"东莞市": "441900",
					"中山市": "442000",
					"潮州市": "445100",
					"揭阳市": "445200",
					"云浮市": "445300",
					"南宁市": "450100",
					"柳州市": "450200",
					"桂林市": "450300",
					"梧州市": "450400",
					"北海市": "450500",
					"防城港市": "450600",
					"钦州市": "450700",
					"贵港市": "450800",
					"玉林市": "450900",
					"百色市": "45100",
					"贺州市": "451100",
					"河池市": "451200",
					"来宾市": "451300",
					"崇左市": "451400",
					"海口市": "460100",
					"三亚市": "460200",
					"三沙市": "460300",
					"成都市": "510100",
					"自贡市": "510300",
					"攀枝花市": "510400",
					"泸州市": "510500",
					"德阳市": "510600",
					"绵阳市": "510700",
					"广元市": "510800",
					"遂宁市": "510900",
					"内江市": "51100",
					"乐山市": "511100",
					"南充市": "511300",
					"眉山市": "511400",
					"宜宾市": "511500",
					"广安市": "511600",
					"达州市": "511700",
					"雅安市": "511800",
					"巴中市": "511900",
					"资阳市": "512000",
					"阿坝藏族羌族自治州": "513200",
					"甘孜藏族自治州": "513300",
					"凉山彝族自治州": "513400",
					"贵阳市": "520100",
					"六盘水市": "520200",
					"遵义市": "520300",
					"安顺市": "520400",
					"黔西南布依族苗族自治州": "522300",
					"黔东南苗族侗族自治州": "522600",
					"黔南布依族苗族自治州": "522700",
					"昆明市": "530100",
					"曲靖市": "530300",
					"玉溪市": "530400",
					"保山市": "530500",
					"昭通市": "530600",
					"丽江市": "530700",
					"普洱市": "530800",
					"临沧市": "530900",
					"楚雄彝族自治州": "532300",
					"红河哈尼族彝族自治州": "532500",
					"文山壮族苗族自治州": "532600",
					"西双版纳傣族自治州": "532800",
					"大理白族自治州": "532900",
					"德宏傣族景颇族自治州": "533100",
					"怒江傈僳族自治州": "533300",
					"迪庆藏族自治州": "533400",
					"拉萨市": "540100",
					"昌都地区": "542100",
					"山南地区": "542200",
					"日喀则地区": "542300",
					"那曲地区": "542400",
					"阿里地区": "542500",
					"林芝地区": "542600",
					"西安市": "610100",
					"铜川市": "610200",
					"宝鸡市": "610300",
					"咸阳市": "610400",
					"渭南市": "610500",
					"延安市": "610600",
					"汉中市": "610700",
					"榆林市": "610800",
					"安康市": "610900",
					"商洛市": "61100",
					"兰州市": "620100",
					"嘉峪关市": "620200",
					"金昌市": "620300",
					"白银市": "620400",
					"天水市": "620500",
					"武威市": "620600",
					"张掖市": "620700",
					"平凉市": "620800",
					"酒泉市": "620900",
					"庆阳市": "62100",
					"定西市": "621100",
					"陇南市": "621200",
					"临夏回族自治州": "622900",
					"甘南藏族自治州": "623000",
					"西宁市": "630100",
					"海东地区": "632100",
					"海北藏族自治州": "632200",
					"黄南藏族自治州": "632300",
					"海南藏族自治州": "632500",
					"果洛藏族自治州": "632600",
					"玉树藏族自治州": "632700",
					"海西蒙古族藏族自治州": "632800",
					"银川市": "640100",
					"石嘴山市": "640200",
					"吴忠市": "640300",
					"固原市": "640400",
					"中卫市": "640500",
					"乌鲁木齐市": "650100",
					"克拉玛依市": "650200",
					"吐鲁番地区": "652100",
					"哈密地区": "652200",
					"昌吉回族自治州": "652300",
					"博尔塔拉蒙古自治州": "652700",
					"巴音郭楞蒙古自治州": "652800",
					"阿克苏地区": "652900",
					"克孜勒苏柯尔克孜自治州": "653000",
					"喀什地区": "653100",
					"和田地区": "653200",
					"伊犁哈萨克自治州": "654000",
					"塔城地区": "654200",
					"阿勒泰地区": "654300",
					"自治区直辖县级行政区划": "659000",
					"台湾省": "71000",
					"香港特别行政区": "810100",
					"澳门特别行政区": "820000"
				};

        var mapGeoData = require('echarts/util/mapData/params');

        //地理坐标
        var geoCoord={
                "海门":[121.15,31.89],
                "鄂尔多斯":[109.781327,39.608266],
                "招远":[120.38,37.35],
                "舟山":[122.207216,29.985295],
                "齐齐哈尔":[123.97,47.33],
                "盐城":[120.13,33.38],
                "赤峰":[118.87,42.28],
                "青岛":[120.33,36.07],
                "乳山":[121.52,36.89],
                "金昌":[102.188043,38.520089],
                "泉州":[118.58,24.93],
                "莱西":[120.53,36.86],
                "日照":[119.46,35.42],
                "胶南":[119.97,35.88],
                "南通":[121.05,32.08],
                "拉萨":[91.11,29.97],
                "云浮":[112.02,22.93],
                "梅州":[116.1,24.55],
                "文登":[122.05,37.2],
                "上海":[121.48,31.22],
                "攀枝花":[101.718637,26.582347],
                "威海":[122.1,37.5],
                "承德":[117.93,40.97],
                "厦门":[118.1,24.46],
                "汕尾":[115.375279,22.786211],
                "潮州":[116.63,23.68],
                "丹东":[124.37,40.13],
                "太仓":[121.1,31.45],
                "曲靖":[103.79,25.51],
                "烟台":[121.39,37.52],
                "福州":[119.3,26.08],
                "瓦房店":[121.979603,39.627114],
                "即墨":[120.45,36.38],
                "抚顺":[123.97,41.97],
                "玉溪":[102.52,24.35],
                "张家口":[114.87,40.82],
                "阳泉":[113.57,37.85],
                "莱州":[119.942327,37.177017],
                "湖州":[120.1,30.86],
                "汕头":[116.69,23.39],
                "昆山":[120.95,31.39],
                "宁波":[121.56,29.86],
                "湛江":[110.359377,21.270708],
                "揭阳":[116.35,23.55],
                "荣成":[122.41,37.16],
                "连云港":[119.16,34.59],
                "葫芦岛":[120.836932,40.711052],
                "常熟":[120.74,31.64],
                "东莞":[113.75,23.04],
                "河源":[114.68,23.73],
                "淮安":[119.15,33.5],
                "泰州":[119.9,32.49],
                "南宁":[108.33,22.84],
                "营口":[122.18,40.65],
                "惠州":[114.4,23.09],
                "江阴":[120.26,31.91],
                "蓬莱":[120.75,37.8],
                "韶关":[113.62,24.84],
                "嘉峪关":[98.289152,39.77313],
                "广州":[113.23,23.16],
                "延安":[109.47,36.6],
                "太原":[112.53,37.87],
                "清远":[113.01,23.7],
                "中山":[113.38,22.52],
                "昆明":[102.73,25.04],
                "寿光":[118.73,36.86],
                "盘锦":[122.070714,41.119997],
                "长治":[113.08,36.18],
                "深圳":[114.07,22.62],
                "珠海":[113.52,22.3],
                "宿迁":[118.3,33.96],
                "咸阳":[108.72,34.36],
                "铜川":[109.11,35.09],
                "平度":[119.97,36.77],
                "佛山":[113.11,23.05],
                "海口":[110.35,20.02],
                "江门":[113.06,22.61],
                "章丘":[117.53,36.72],
                "肇庆":[112.44,23.05],
                "大连":[121.62,38.92],
                "临汾":[111.5,36.08],
                "吴江":[120.63,31.16],
                "石嘴山":[106.39,39.04],
                "沈阳":[123.38,41.8],
                "苏州":[120.62,31.32],
                "茂名":[110.88,21.68],
                "嘉兴":[120.76,30.77],
                "长春":[125.35,43.88],
                "胶州":[120.03336,36.264622],
                "银川":[106.27,38.47],
                "张家港":[120.555821,31.875428],
                "三门峡":[111.19,34.76],
                "锦州":[121.15,41.13],
                "南昌":[115.89,28.68],
                "柳州":[109.4,24.33],
                "三亚":[109.511909,18.252847],
                "自贡":[104.778442,29.33903],
                "吉林":[126.57,43.87],
                "阳江":[111.95,21.85],
                "泸州":[105.39,28.91],
                "西宁":[101.74,36.56],
                "宜宾":[104.56,29.77],
                "呼和浩特":[111.65,40.82],
                "成都":[104.06,30.67],
                "大同":[113.3,40.12],
                "镇江":[119.44,32.2],
                "桂林":[110.28,25.29],
                "张家界":[110.479191,29.117096],
                "宜兴":[119.82,31.36],
                "北海":[109.12,21.49],
                "西安":[108.95,34.27],
                "金坛":[119.56,31.74],
                "东营":[118.49,37.46],
                "牡丹江":[129.58,44.6],
                "遵义":[106.9,27.7],
                "绍兴":[120.58,30.01],
                "扬州":[119.42,32.39],
                "常州":[119.95,31.79],
                "潍坊":[119.1,36.62],
                "重庆":[106.54,29.59],
                "台州":[121.420757,28.656386],
                "南京":[118.78,32.04],
                "滨州":[118.03,37.36],
                "贵阳":[106.71,26.57],
                "无锡":[120.29,31.59],
                "本溪":[123.73,41.3],
                "克拉玛依":[84.77,45.59],
                "渭南":[109.5,34.52],
                "马鞍山":[118.48,31.56],
                "宝鸡":[107.15,34.38],
                "焦作":[113.21,35.24],
                "句容":[119.16,31.95],
                "北京":[116.46,39.92],
                "徐州":[117.2,34.26],
                "衡水":[115.72,37.72],
                "包头":[110,40.58],
                "绵阳":[104.73,31.48],
                "乌鲁木齐":[87.68,43.77],
                "枣庄":[117.57,34.86],
                "杭州":[120.19,30.26],
                "淄博":[118.05,36.78],
                "鞍山":[122.85,41.12],
                "溧阳":[119.48,31.43],
                "库尔勒":[86.06,41.68],
                "安阳":[114.35,36.1],
                "开封":[114.35,34.79],
                "济南":[117,36.65],
                "德阳":[104.37,31.13],
                "温州":[120.65,28.01],
                "九江":[115.97,29.71],
                "邯郸":[114.47,36.6],
                "临安":[119.72,30.23],
                "兰州":[103.73,36.03],
                "沧州":[116.83,38.33],
                "临沂":[118.35,35.05],
                "南充":[106.110698,30.837793],
                "天津":[117.2,39.13],
                "富阳":[119.95,30.07],
                "泰安":[117.13,36.18],
                "诸暨":[120.23,29.71],
                "郑州":[113.65,34.76],
                "哈尔滨":[126.63,45.75],
                "聊城":[115.97,36.45],
                "芜湖":[118.38,31.33],
                "唐山":[118.02,39.63],
                "平顶山":[113.29,33.75],
                "邢台":[114.48,37.05],
                "德州":[116.29,37.45],
                "济宁":[116.59,35.38],
                "荆州":[112.239741,30.335165],
                "宜昌":[111.3,30.7],
                "义乌":[120.06,29.32],
                "丽水":[119.92,28.45],
                "洛阳":[112.44,34.7],
                "秦皇岛":[119.57,39.95],
                "株洲":[113.16,27.83],
                "石家庄":[114.48,38.03],
                "莱芜":[117.67,36.19],
                "常德":[111.69,29.05],
                "保定":[115.48,38.85],
                "湘潭":[112.91,27.87],
                "金华":[119.64,29.12],
                "岳阳":[113.09,29.37],
                "长沙":[113,28.21],
                "衢州":[118.88,28.97],
                "廊坊":[116.7,39.53],
                "菏泽":[115.480656,35.23375],
                "合肥":[117.27,31.86],
                "武汉":[114.31,30.52],
                "大庆":[125.03,46.58]
            };

				for(var i in cityMap) {
					mapType.push(i);
					// 自定义扩展图表类型
					mapGeoData.params[i] = {
							getGeoJson: (function(c) {
								var geoJsonName = cityMap[c];

								return function(callback) {
									$.getJSON('echarts/geoJson/china-main-city/' + geoJsonName + '.json', callback);
								}
							})(i)
					};
				}

				myChartMain.on(ecConfig.EVENT.MAP_SELECTED, function(param) {
  					var len = mapType.length;  //所有的城市名
  					var mt = param.target;  //获取相应的区域名
  					var onOff = false;
  					for(var i = 0; i < len; i++) {
  						if(mt == mapType[i]) {
  							onOff= true;
  							mt = mapType[i];
  						}
  					}
  					if(!onOff) {
  						mt = 'china';
  						option.title.text = "中国区域";
  					}else{
  						option.title.text = mt+"区域";
  					}

						for(var j=0;j<option.series.length;j++){
							option.series[j].mapType=mt;
							console.log(mt)
							//console.log(option.series[j].markPoint.data)

						}

						if(mt=='china'){
							//mt='';
							option.title.subtext = '（点击切换）';
							option.tooltip.formatter = '点击进入该省<br/>{b}';
						}else{
							option.title.subtext = mt + '（点击切换）';
							option.tooltip.formatter = '点击返回全国<br/>{b}';
						}

  					myChartMain.setOption(option, true);
				});


			function randomData() {
        	return Math.round(Math.random()*1000);
      };

			var option = {
          backgroundColor: 'none',
          color: [
              'rgba(0,128,0,1)',  //在线
              'rgba(255,0,0,1)' //离线
          ],
					title: {
						text: '中国区域',
						x: 'center',
            y:'top',
						subtext:'（点击切换）',
            textStyle:{
              fontSize:'18',
              color:'#0189a3'
            }
					},
					tooltip: {
						trigger: 'item',
						formatter:'{b}'
					},
					legend: {
              orient: 'vertical',
              x:'20',
              y:'top',
              data:['在线设备','离线设备'],
              selectedMode:false,
              textStyle : {
                  color: 'auto'
              }
          },
					toolbox: {   //工具箱
              show :false,
              orient : 'vertical',
              x: 'right',
              y: 'center',
              feature : {
                  mark : {show: true},
                  dataView : {show: true, readOnly: false},
                  restore : {show: true},
                  saveAsImage : {show: true}
              }
          },
					series: [
              {
      						name: '在线设备',
      						type: 'map',
      						mapType: 'china',
      						selectedMode: 'single',
                  symbolSize : 1,
      						itemStyle: {
      							normal: {
                      borderColor:'#03757b',   //地图边界线
                      borderWidth:2,
                      areaStyle:{  //地区颜色
                          color: '#041027'
                      },
      								label: {
      									show: false,//是否显示城市名字
      									textStyle: {
      										color: "rgb(249, 249, 249)"
      									}
      								},
      							},
      							emphasis: { color:'#FF9933',label: { show: true } },
      						},
									markLine : {
                      smooth:true,
                      effect : {
                          show: true,
                          scaleSize: 1,
                          period: 30,
                          color: '#fff',
                          shadowBlur: 10
                      },
                      itemStyle : {
                          normal: {
                              borderWidth:1,
                              lineStyle: {
                                  type: 'solid',
                                  shadowBlur: 10
                              }
                          }
                      },
                      data : []
                  },
									markPoint : {

                        symbol:'circle',
                        symbolSize : 3,
                        effect : {          //标注图形炫光特效
                            show: true,      //关闭
                            shadowBlur : 3
                        },
                        itemStyle:{
                            normal:{
                                label:{show:false}
                            },
                            emphasis: {
                                label:{
                                  show:true,
                                  position:'top'
                                }
                            }
                        },
                        data:[ //离线数据
                            {name:'长沙'},
														{name:'深圳'}
                        ]
                  },
									geoCoord:geoCoord,
									data:[],
									/*
      						data: [
      							{ name: '湖南', randomData() },
      							{ name: '湖北', randomData() },
      							{ name: '广东', randomData() },
      							{ name: '青海', randomData() },
      							{ name: '四川', randomData() },
      							{ name: '海南', randomData() },
      							{ name: '陕西', randomData() },
      							{ name: '甘肃', randomData() },
      							{ name: '云南', randomData() },
      							{ name: '黑龙江', randomData() },
      							{ name: '贵州', randomData() },
      							{ name: '山东', randomData() },
      							{ name: '江西', randomData() },
      							{ name: '河南', randomData() },
      							{ name: '河北', randomData() },
      							{ name: '山西', randomData() },
      							{ name: '安徽', randomData() },
      							{ name: '福建', randomData() },
      							{ name: '浙江', randomData() },
      							{ name: '江苏', randomData() },
      							{ name: '吉林', randomData() },
      							{ name: '辽宁', randomData() },
      							{ name: '台湾', randomData() },
      							{ name: '新疆', randomData() },
      							{ name: '广西', randomData() },
      							{ name: '宁夏', randomData() },
      							{ name: '内蒙古', randomData() },
      							{ name: '西藏', randomData() },
      							{ name: '北京', randomData() },
      							{ name: '天津', randomData() },
      							{ name: '重庆', randomData() },
      							{ name: '上海', randomData() },
      							{ name: '广州', randomData() },
      							{ name: '重庆市', randomData() },
      							{ name: '北京市', randomData() },
      							{ name: '天津市', randomData() },
      							{ name: '上海市', randomData() },
      							{ name: '香港', randomData() },
      							{ name: '澳门', randomData() },
      							{ name: '巴音郭楞蒙古自治州', randomData() },
      							{ name: '和田地区', randomData() },
      							{ name: '哈密地区', randomData() },
      							{ name: '阿克苏地区', randomData() },
      							{ name: '阿勒泰地区', randomData() },
      							{ name: '喀什地区', randomData() },
      							{ name: '塔城地区', randomData() },
      							{ name: '昌吉回族自治州', randomData() },
      							{ name: '克孜勒苏柯尔克孜自治州', randomData() },
      							{ name: '吐鲁番地区', randomData() },
      							{ name: '伊犁哈萨克自治州', randomData() },
      							{ name: '博尔塔拉蒙古自治州', randomData() },
      							{ name: '乌鲁木齐市', randomData() },
      							{ name: '克拉玛依市', randomData() },
      							{ name: '阿拉尔市', randomData() },
      							{ name: '图木舒克市', randomData() },
      							{ name: '五家渠市', randomData() },
      							{ name: '石河子市', randomData() },
      							{ name: '那曲地区', randomData() },
      							{ name: '阿里地区', randomData() },
      							{ name: '日喀则地区', randomData() },
      							{ name: '林芝地区', randomData() },
      							{ name: '昌都地区', randomData() },
      							{ name: '山南地区', randomData() },
      							{ name: '拉萨市', randomData() },
      							{ name: '呼伦贝尔市', randomData() },
      							{ name: '阿拉善盟', randomData() },
      							{ name: '锡林郭勒盟', randomData() },
      							{ name: '鄂尔多斯市', randomData() },
      							{ name: '赤峰市', randomData() },
      							{ name: '巴彦淖尔市', randomData() },
      							{ name: '通辽市', randomData() },
      							{ name: '乌兰察布市', randomData() },
      							{ name: '兴安盟', randomData() },
      							{ name: '包头市', randomData() },
      							{ name: '呼和浩特市', randomData() },
      							{ name: '乌海市', randomData() },
      							{ name: '海西蒙古族藏族自治州', randomData() },
      							{ name: '玉树藏族自治州', randomData() },
      							{ name: '果洛藏族自治州', randomData() },
      							{ name: '海南藏族自治州', randomData() },
      							{ name: '海北藏族自治州', randomData() },
      							{ name: '黄南藏族自治州', randomData() },
      							{ name: '海东地区', randomData() },
      							{ name: '西宁市', randomData() },
      							{ name: '甘孜藏族自治州', randomData() },
      							{ name: '阿坝藏族羌族自治州', randomData() },
      							{ name: '凉山彝族自治州', randomData() },
      							{ name: '绵阳市', randomData() },
      							{ name: '达州市', randomData() },
      							{ name: '广元市', randomData() },
      							{ name: '雅安市', randomData() },
      							{ name: '宜宾市', randomData() },
      							{ name: '乐山市', randomData() },
      							{ name: '南充市', randomData() },
      							{ name: '巴中市', randomData() },
      							{ name: '泸州市', randomData() },
      							{ name: '成都市', randomData() },
      							{ name: '资阳市', randomData() },
      							{ name: '攀枝花市', randomData() },
      							{ name: '眉山市', randomData() },
      							{ name: '广安市', randomData() },
      							{ name: '德阳市', randomData() },
      							{ name: '内江市', randomData() },
      							{ name: '遂宁市', randomData() },
      							{ name: '自贡市', randomData() },
      							{ name: '黑河市', randomData() },
      							{ name: '大兴安岭地区', randomData() },
      							{ name: '哈尔滨市', randomData() },
      							{ name: '齐齐哈尔市', randomData() },
      							{ name: '牡丹江市', randomData() },
      							{ name: '绥化市', randomData() },
      							{ name: '伊春市', randomData() },
      							{ name: '佳木斯市', randomData() },
      							{ name: '鸡西市', randomData() },
      							{ name: '双鸭山市', randomData() },
      							{ name: '大庆市', randomData() },
      							{ name: '鹤岗市', randomData() },
      							{ name: '七台河市', randomData() },
      							{ name: '酒泉市', randomData() },
      							{ name: '张掖市', randomData() },
      							{ name: '甘南藏族自治州', randomData() },
      							{ name: '武威市', randomData() },
      							{ name: '陇南市', randomData() },
      							{ name: '庆阳市', randomData() },
      							{ name: '白银市', randomData() },
      							{ name: '定西市', randomData() },
      							{ name: '天水市', randomData() },
      							{ name: '兰州市', randomData() },
      							{ name: '平凉市', randomData() },
      							{ name: '临夏回族自治州', randomData() },
      							{ name: '金昌市', randomData() },
      							{ name: '嘉峪关市', randomData() },
      							{ name: '普洱市', randomData() },
      							{ name: '红河哈尼族彝族自治州', randomData() },
      							{ name: '文山壮族苗族自治州', randomData() },
      							{ name: '曲靖市', randomData() },
      							{ name: '楚雄彝族自治州', randomData() },
      							{ name: '大理白族自治州', randomData() },
      							{ name: '临沧市', randomData() },
      							{ name: '迪庆藏族自治州', randomData() },
      							{ name: '昭通市', randomData() },
      							{ name: '昆明市', randomData() },
      							{ name: '丽江市', randomData() },
      							{ name: '西双版纳傣族自治州', randomData() },
      							{ name: '保山市', randomData() },
      							{ name: '玉溪市', randomData() },
      							{ name: '怒江傈僳族自治州', randomData() },
      							{ name: '德宏傣族景颇族自治州', randomData() },
      							{ name: '百色市', randomData() },
      							{ name: '河池市', randomData() },
      							{ name: '桂林市', randomData() },
      							{ name: '南宁市', randomData() },
      							{ name: '柳州市', randomData() },
      							{ name: '崇左市', randomData() },
      							{ name: '来宾市', randomData() },
      							{ name: '玉林市', randomData() },
      							{ name: '梧州市', randomData() },
      							{ name: '贺州市', randomData() },
      							{ name: '钦州市', randomData() },
      							{ name: '贵港市', randomData() },
      							{ name: '防城港市', randomData() },
      							{ name: '北海市', randomData() },
      							{ name: '怀化市', randomData() },
      							{ name: '永州市', randomData() },
      							{ name: '邵阳市', randomData() },
      							{ name: '郴州市', randomData() },
      							{ name: '常德市', randomData() },
      							{ name: '湘西土家族苗族自治州', randomData() },
      							{ name: '衡阳市', randomData() },
      							{ name: '岳阳市', randomData() },
      							{ name: '益阳市', randomData() },
      							{ name: '长沙市', randomData() },
      							{ name: '株洲市', randomData() },
      							{ name: '张家界市', randomData() },
      							{ name: '娄底市', randomData() },
      							{ name: '湘潭市', randomData() },
      							{ name: '榆林市', randomData() },
      							{ name: '延安市', randomData() },
      							{ name: '汉中市', randomData() },
      							{ name: '安康市', randomData() },
      							{ name: '商洛市', randomData() },
      							{ name: '宝鸡市', randomData() },
      							{ name: '渭南市', randomData() },
      							{ name: '咸阳市', randomData() },
      							{ name: '西安市', randomData() },
      							{ name: '铜川市', randomData() },
      							{ name: '清远市', randomData() },
      							{ name: '韶关市', randomData() },
      							{ name: '湛江市', randomData() },
      							{ name: '梅州市', randomData() },
      							{ name: '河源市', randomData() },
      							{ name: '肇庆市', randomData() },
      							{ name: '惠州市', randomData() },
      							{ name: '茂名市', randomData() },
      							{ name: '江门市', randomData() },
      							{ name: '阳江市', randomData() },
      							{ name: '云浮市', randomData() },
      							{ name: '广州市', randomData() },
      							{ name: '汕尾市', randomData() },
      							{ name: '揭阳市', randomData() },
      							{ name: '珠海市', randomData() },
      							{ name: '佛山市', randomData() },
      							{ name: '潮州市', randomData() },
      							{ name: '汕头市', randomData() },
      							{ name: '深圳市', randomData() },
      							{ name: '东莞市', randomData() },
      							{ name: '中山市', randomData() },
      							{ name: '延边朝鲜族自治州', randomData() },
      							{ name: '吉林市', randomData() },
      							{ name: '白城市', randomData() },
      							{ name: '松原市', randomData() },
      							{ name: '长春市', randomData() },
      							{ name: '白山市', randomData() },
      							{ name: '通化市', randomData() },
      							{ name: '四平市', randomData() },
      							{ name: '辽源市', randomData() },
      							{ name: '承德市', randomData() },
      							{ name: '张家口市', randomData() },
      							{ name: '保定市', randomData() },
      							{ name: '唐山市', randomData() },
      							{ name: '沧州市', randomData() },
      							{ name: '石家庄市', randomData() },
      							{ name: '邢台市', randomData() },
      							{ name: '邯郸市', randomData() },
      							{ name: '秦皇岛市', randomData() },
      							{ name: '衡水市', randomData() },
      							{ name: '廊坊市', randomData() },
      							{ name: '恩施土家族苗族自治州', randomData() },
      							{ name: '十堰市', randomData() },
      							{ name: '宜昌市', randomData() },
      							{ name: '襄樊市', randomData() },
      							{ name: '黄冈市', randomData() },
      							{ name: '荆州市', randomData() },
      							{ name: '荆门市', randomData() },
      							{ name: '咸宁市', randomData() },
      							{ name: '随州市', randomData() },
      							{ name: '孝感市', randomData() },
      							{ name: '武汉市', randomData() },
      							{ name: '黄石市', randomData() },
      							{ name: '神农架林区', randomData() },
      							{ name: '天门市', randomData() },
      							{ name: '仙桃市', randomData() },
      							{ name: '潜江市', randomData() },
      							{ name: '鄂州市', randomData() },
      							{ name: '遵义市', randomData() },
      							{ name: '黔东南苗族侗族自治州', randomData() },
      							{ name: '毕节地区', randomData() },
      							{ name: '黔南布依族苗族自治州', randomData() },
      							{ name: '铜仁地区', randomData() },
      							{ name: '黔西南布依族苗族自治州', randomData() },
      							{ name: '六盘水市', randomData() },
      							{ name: '安顺市', randomData() },
      							{ name: '贵阳市', randomData() },
      							{ name: '烟台市', randomData() },
      							{ name: '临沂市', randomData() },
      							{ name: '潍坊市', randomData() },
      							{ name: '青岛市', randomData() },
      							{ name: '菏泽市', randomData() },
      							{ name: '济宁市', randomData() },
      							{ name: '德州市', randomData() },
      							{ name: '滨州市', randomData() },
      							{ name: '聊城市', randomData() },
      							{ name: '东营市', randomData() },
      							{ name: '济南市', randomData() },
      							{ name: '泰安市', randomData() },
      							{ name: '威海市', randomData() },
      							{ name: '日照市', randomData() },
      							{ name: '淄博市', randomData() },
      							{ name: '枣庄市', randomData() },
      							{ name: '莱芜市', randomData() },
      							{ name: '赣州市', randomData() },
      							{ name: '吉安市', randomData() },
      							{ name: '上饶市', randomData() },
      							{ name: '九江市', randomData() },
      							{ name: '抚州市', randomData() },
      							{ name: '宜春市', randomData() },
      							{ name: '南昌市', randomData() },
      							{ name: '景德镇市', randomData() },
      							{ name: '萍乡市', randomData() },
      							{ name: '鹰潭市', randomData() },
      							{ name: '新余市', randomData() },
      							{ name: '南阳市', randomData() },
      							{ name: '信阳市', randomData() },
      							{ name: '洛阳市', randomData() },
      							{ name: '驻马店市', randomData() },
      							{ name: '周口市', randomData() },
      							{ name: '商丘市', randomData() },
      							{ name: '三门峡市', randomData() },
      							{ name: '新乡市', randomData() },
      							{ name: '平顶山市', randomData() },
      							{ name: '郑州市', randomData() },
      							{ name: '安阳市', randomData() },
      							{ name: '开封市', randomData() },
      							{ name: '焦作市', randomData() },
      							{ name: '许昌市', randomData() },
      							{ name: '濮阳市', randomData() },
      							{ name: '漯河市', randomData() },
      							{ name: '鹤壁市', randomData() },
      							{ name: '大连市', randomData() },
      							{ name: '朝阳市', randomData() },
      							{ name: '丹东市', randomData() },
      							{ name: '铁岭市', randomData() },
      							{ name: '沈阳市', randomData() },
      							{ name: '抚顺市', randomData() },
      							{ name: '葫芦岛市', randomData() },
      							{ name: '阜新市', randomData() },
      							{ name: '锦州市', randomData() },
      							{ name: '鞍山市', randomData() },
      							{ name: '本溪市', randomData() },
      							{ name: '营口市', randomData() },
      							{ name: '辽阳市', randomData() },
      							{ name: '盘锦市', randomData() },
      							{ name: '忻州市', randomData() },
      							{ name: '吕梁市', randomData() },
      							{ name: '临汾市', randomData() },
      							{ name: '晋中市', randomData() },
      							{ name: '运城市', randomData() },
      							{ name: '大同市', randomData() },
      							{ name: '长治市', randomData() },
      							{ name: '朔州市', randomData() },
      							{ name: '晋城市', randomData() },
      							{ name: '太原市', randomData() },
      							{ name: '阳泉市', randomData() },
      							{ name: '六安市', randomData() },
      							{ name: '安庆市', randomData() },
      							{ name: '滁州市', randomData() },
      							{ name: '宣城市', randomData() },
      							{ name: '阜阳市', randomData() },
      							{ name: '宿州市', randomData() },
      							{ name: '黄山市', randomData() },
      							{ name: '巢湖市', randomData() },
      							{ name: '亳州市', randomData() },
      							{ name: '池州市', randomData() },
      							{ name: '合肥市', randomData() },
      							{ name: '蚌埠市', randomData() },
      							{ name: '芜湖市', randomData() },
      							{ name: '淮北市', randomData() },
      							{ name: '淮南市', randomData() },
      							{ name: '马鞍山市', randomData() },
      							{ name: '铜陵市', randomData() },
      							{ name: '南平市', randomData() },
      							{ name: '三明市', randomData() },
      							{ name: '龙岩市', randomData() },
      							{ name: '宁德市', randomData() },
      							{ name: '福州市', randomData() },
      							{ name: '漳州市', randomData() },
      							{ name: '泉州市', randomData() },
      							{ name: '莆田市', randomData() },
      							{ name: '厦门市', randomData() },
      							{ name: '丽水市', randomData() },
      							{ name: '杭州市', randomData() },
      							{ name: '温州市', randomData() },
      							{ name: '宁波市', randomData() },
      							{ name: '舟山市', randomData() },
      							{ name: '台州市', randomData() },
      							{ name: '金华市', randomData() },
      							{ name: '衢州市', randomData() },
      							{ name: '绍兴市', randomData() },
      							{ name: '嘉兴市', randomData() },
      							{ name: '湖州市', randomData() },
      							{ name: '盐城市', randomData() },
      							{ name: '徐州市', randomData() },
      							{ name: '南通市', randomData() },
      							{ name: '淮安市', randomData() },
      							{ name: '苏州市', randomData() },
      							{ name: '宿迁市', randomData() },
      							{ name: '连云港市', randomData() },
      							{ name: '扬州市', randomData() },
      							{ name: '南京市', randomData() },
      							{ name: '泰州市', randomData() },
      							{ name: '无锡市', randomData() },
      							{ name: '常州市', randomData() },
      							{ name: '镇江市', randomData() },
      							{ name: '吴忠市', randomData() },
      							{ name: '中卫市', randomData() },
      							{ name: '固原市', randomData() },
      							{ name: '银川市', randomData() },
      							{ name: '石嘴山市', randomData() },
      							{ name: '儋州市', randomData() },
      							{ name: '文昌市', randomData() },
      							{ name: '乐东黎族自治县', randomData() },
      							{ name: '三亚市', randomData() },
      							{ name: '琼中黎族苗族自治县', randomData() },
      							{ name: '东方市', randomData() },
      							{ name: '海口市', randomData() },
      							{ name: '万宁市', randomData() },
      							{ name: '澄迈县', randomData() },
      							{ name: '白沙黎族自治县', randomData() },
      							{ name: '琼海市', randomData() },
      							{ name: '昌江黎族自治县', randomData() },
      							{ name: '临高县', randomData() },
      							{ name: '陵水黎族自治县', randomData() },
      							{ name: '屯昌县', randomData() },
      							{ name: '定安县', randomData() },
      							{ name: '保亭黎族苗族自治县', randomData() },
      							{ name: '五指山市', randomData() },
      							{ name: '长沙县', randomData() },
      							{ name: '宁乡县', randomData() },
      							{ name: '浏阳市', randomData() },
      							{ name: '长沙县', randomData() },
      							{ name: '开福区', randomData() },
      							{ name: '芙蓉区', randomData() },
      							{ name: '雨花区', randomData() },
      							{ name: '望城区', randomData() },
      							{ name: '天心区', randomData() },
      							{ name: '岳麓区', randomData() },
      						]
									,
									*/
								},
								{
      						name: '离线设备',
      						type: 'map',
      						mapType: 'china',
      						selectedMode: 'single',
                  symbolSize : 1,
      						itemStyle: {
      							normal: {
                      borderColor:'#03757b',   //地图边界线
                      borderWidth:2,
                      areaStyle:{  //地区颜色
                          color: '#041027'
                      },
      								label: {
      									show: false,//是否显示城市名字
      									textStyle: {
      										color: "rgb(249, 249, 249)"
      									}
      								},
      							},
      							emphasis: { color:'#FF9933',label: { show: true } },
      						},
									markLine : {
                      smooth:true,
                      effect : {
                          show: true,
                          scaleSize: 1,
                          period: 30,
                          color: '#fff',
                          shadowBlur: 10
                      },
                      itemStyle : {
                          normal: {
                              borderWidth:1,
                              lineStyle: {
                                  type: 'solid',
                                  shadowBlur: 10
                              }
                          }
                      },
                      data : []
                  },
									markPoint : {
                        symbol:'circle',
                        symbolSize : 3,
                        effect : {          //标注图形炫光特效
                            show: true,      //关闭
                            shadowBlur : 3
                        },
                        itemStyle:{
                            normal:{
                                label:{show:false}
                            },
                            emphasis: {
                                label:{
                                  show:true,
                                  position:'top'
                                }
                            }
                        },
                        data : [
                          {name:'福州'},
                          {name:'太原'},
                          {name:'重庆'}
                      ]
                  },
									geoCoord:geoCoord,
									data:[]
								}

          ]
				};

        var centerMap=option;
        myChartMain.showLoading({
          text:'地图加载中...',
          effect:'spin',
          itemStyle:{
            fontSize:16
          }
        });

        clearTimeout(loadingCenter);
        var loadingCenter=setTimeout(function (){
            myChartMain.hideLoading();
            myChartMain.setOption(centerMap);
        }, 1000);


        myChartMain.on('click', function (params) {
					//console.log(option.series)
        });


			}
);
